### PR TITLE
Bump Typographic and Axis versions

### LINKED ISSUE #4: Outdated Typographic
Great package so far, but the Typographic is currently really outdated.
I follow official Typographic instructions and I write 

```
@import 'typographic'
typographic()
```

And it does not apply the styles. Probably the package has changed greatly since it was included first here. Please update it!

Edit: I have fixed that for myself by adding a meteor bower package and installing typograhpic from it and then importing it with 
`@import '.meteor/local/bower/typographic/stylus/typographic'`
which works, but still a minor issue exists.

### PR DESCRIPTION
**Pull request by cryptoquick**
Also, update Typographic test, README, and History.

I didn't bump the version because I think that merited some discussion. Typographic has changed significantly since we first included it a month ago. I don't know if many people have started using the new feature, but in updating the test, I realized the interface has changed a great deal, and could be a breaking change for some people. It would be more 'semver' to bump to `2.0.0` in light of that, but then again, people might not know to upgrade, particularly because Meteor doesn't share the same tools as npm users have (such as David) to detect that they have out-of-date packages. It's a tough decision.

Fixes #4 .

### CODE REVIEW

**Comment by sriprasanna** [comment]
Any plan to merge this pull request?

**Comment by cryptoquick** [comment]
I could merge it, but I can't publish the new version. @mquandalle ?

**Comment by mquandalle** [comment]
Hello @cryptoquick, I added you as an atmosphere maintainer.

**Comment by sriprasanna** [comment]
Great! Thanks for this. You should bump up the package version as well so that we can update the packages and take advantage of these changes. I would be happy to change it and raise a pull request unless there is an alternative plan.

**Comment by cryptoquick** [comment]
This should be good now. :smile_cat: 
I updated the packages again and I published the new version.

**Comment by sriprasanna** [comment]
Thanks @cryptoquick

**Pull request merged**
